spring.application.name=cloud-file-storage

server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/cloud_storage
spring.datasource.username=postgres
spring.datasource.password=1378@bts
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT
jwt.secret=Q2xvdWRTdG9yYWdlU2VjcmV0S2V5Rm9ySldUQXV0aGVudGljYXRpb24yMDI2
jwt.expiration=86400000
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# =========================
# EMAIL CONFIGURATION
# =========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_GMAIL@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true


spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.host=smtp.gmail.com
spring.mail.port=465

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000